# Generated by Django 2.2.2 on 2019-06-18 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('data_de_Nascimento', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pai')),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mãe')),
                ('data_de_registro', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Data de cadastro')),
                ('cpf', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=255, null=True, verbose_name='RG')),
                ('profissao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profissao')),
                ('etnia', models.CharField(max_length=32, verbose_name='Etnia')),
                ('sexo', models.CharField(max_length=24)),
                ('naturalidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Naturalidade')),
                ('uf', models.CharField(max_length=32, verbose_name='UF')),
                ('cidade', models.CharField(max_length=32, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=32, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=32, verbose_name='Rua')),
                ('numro', models.IntegerField(verbose_name='Nº')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('cel', models.CharField(max_length=11, verbose_name='Celular')),
                ('Fixo', models.CharField(max_length=11, verbose_name='Fixo')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profissional responsável')),
            ],
            options={
                'verbose_name': 'Prontuario de atendimento integral',
                'verbose_name_plural': 'Prontuarios de atendimento integral',
            },
        ),
    ]
